### ISSUE TITLE
override CRI-O script to update for 3 master configuration 

### ISSUE THREAD

**Issue by Ronanb3** [IBM-ICP4D/cloud-pak-ocp-4#2]
Here is the configuration in this case : changer worker into master in labels

```
cat << EOF > /tmp/51-worker-cp4d-crio-conf.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
 labels:
   machineconfiguration.openshift.io/role: master
 name: 51-worker-cp4d-crio-conf
spec:
 config:
   ignition:
     version: 2.2.0
   storage:
     files:
     - contents:
         source: data:,${crio_conf}
       filesystem: root
       mode: 0644
       path: /etc/crio/crio.conf
EOF

```
