### ISSUE TITLE
Support IPI install

### ISSUE THREAD

**Issue by fketelaars** [IBM-ICP4D/cloud-pak-ocp-4#9]
IPI installs with vSphere are now supported. It still is beneficial to have the Ansible scripts prepare the bastion and cluster nodes with the DNS server and settings, NTP configuration, proxies, etc. Make the following changes to support IPI:
* New property in inventory file: installation_type, defaults to UPI
* Generate different installation config 
* haproxy configuration should point to VIPs
* dnsmasq configuration should not generate DHCP MAC addresses
* Include configuration of the masters and workers (and maybe other types too)
* Skip OCP installation steps in case of IPI, also in documentation

**Comment by fketelaars** [comment]
Sample install-config.yaml:
```
apiVersion: v1
baseDomain: mic.ibm.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    vsphere:
      cpus: 12
      coresPerSocket: 2
      memoryMB: 65536
      osDisk:
        diskSizeGB: 120
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp46
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 10.99.92.51
    cluster: Cluster1
    datacenter: Datacenter1
    defaultDatastore: Datastore1
    ingressVIP: 10.99.92.52
    network: VM Network
    password: ...
    username: ...
    vCenter: 10.99.92.13
publish: External
pullSecret: ...
sshKey: |
  ssh-rsa ...
```
